[tool.poetry]
name = "tester"
version = "0.1.0"
description = ""
authors = ["Tadgh <garygrantgraham@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.32.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
